version: '3'
services:
  nginx:
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
  web:
    image: node:8
    container_name: gamevote_node
    volumes:
      - ./www:/usr/src/app
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: npm start
  db:
    image: postgres
    volumes:
      - ./db/docker-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/my-scripts
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: games
      POSTGRES_USER: games
      POSTGRES_PASSWORD: password
    command: postgres -c work_mem=64MB
