version: '3'
services:
  nginx:
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    command: bash -c 'npm install && npm start'
