version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: gamevote_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - web
  web:
    build:
      context: www
      dockerfile: Dockerfile
    image: gamevote_node
    container_name: gamevote_node
    ports:
      - 8080:8080
  api:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgresql://games:password@db/games
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/my-scripts
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: games
      POSTGRES_USER: games
      POSTGRES_PASSWORD: password
    command: postgres -c work_mem=64MB
