version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: gamevote_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    image: node:8
    container_name: gamevote_node
    volumes:
      - ./www:/usr/src/app
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: npm start
  api:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgresql://games:password@db/games
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db/docker-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/my-scripts
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: games
      POSTGRES_USER: games
      POSTGRES_PASSWORD: password
    command: postgres -c work_mem=64MB
