version: '3'
services:
  web:
    environment:
      DB_CONN_STR: postgresql://${PGUSER}:${PGPASSWORD}@db/${PGDATABASE}
  api:
    environment:
      PGRST_DB_URI: postgresql://authenticator:auth@db/${PGDATABASE}
  db:
    image: postgres
    volumes:
      - ./db/docker-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/my-scripts
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    command: postgres -c work_mem=64MB
