version: '3'
services:
  web:
    environment:
      DB_CONN_STR: postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
  api:
    environment:
      PGRST_DB_URI: postgresql://authenticator:auth@${PGHOST}/${PGDATABASE}
