version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: gamevote_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - web
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    image: node:8
    container_name: gamevote_node
    volumes:
      - ./www:/usr/src/app
    ports:
      - 8080:8080
    working_dir: /usr/src/app
  api:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    environment:
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anon
